/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as DoshaRouteImport } from './routes/dosha'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as NourishRouteImport } from './routes/nourish'
import { Route as PathRouteImport } from './routes/path'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as NourishIndexRouteImport } from './routes/nourish.index'
import { Route as NourishRecipeIdRouteImport } from './routes/nourish.$recipeId'
import { Route as PathIndexRouteImport } from './routes/path.index'
import { Route as PathDateRouteImport } from './routes/path.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const DoshaRoute = DoshaRouteImport.update({
  id: '/dosha',
  path: '/dosha',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const NourishRoute = NourishRouteImport.update({
  id: '/nourish',
  path: '/nourish',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const NourishIndexRoute = NourishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NourishRoute,
} as any)
const NourishRecipeIdRoute = NourishRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => NourishRoute,
} as any)
const PathIndexRoute = PathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathRoute,
} as any)
const PathDateRoute = PathDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => PathRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathe': typeof BreatheRoute
  '/dosha': typeof DoshaRoute
  '/journal': typeof JournalRoute
  '/nourish': typeof NourishRouteWithChildren
  '/path': typeof PathRouteWithChildren
  '/reset': typeof ResetRoute
  '/nourish/$recipeId': typeof NourishRecipeIdRoute
  '/path/$date': typeof PathDateRoute
  '/nourish/': typeof NourishIndexRoute
  '/path/': typeof PathIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathe': typeof BreatheRoute
  '/dosha': typeof DoshaRoute
  '/journal': typeof JournalRoute
  '/reset': typeof ResetRoute
  '/nourish/$recipeId': typeof NourishRecipeIdRoute
  '/path/$date': typeof PathDateRoute
  '/nourish': typeof NourishIndexRoute
  '/path': typeof PathIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breathe': typeof BreatheRoute
  '/dosha': typeof DoshaRoute
  '/journal': typeof JournalRoute
  '/nourish': typeof NourishRouteWithChildren
  '/path': typeof PathRouteWithChildren
  '/reset': typeof ResetRoute
  '/nourish/$recipeId': typeof NourishRecipeIdRoute
  '/path/$date': typeof PathDateRoute
  '/nourish/': typeof NourishIndexRoute
  '/path/': typeof PathIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/breathe'
    | '/dosha'
    | '/journal'
    | '/nourish'
    | '/path'
    | '/reset'
    | '/nourish/$recipeId'
    | '/path/$date'
    | '/nourish/'
    | '/path/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/breathe'
    | '/dosha'
    | '/journal'
    | '/reset'
    | '/nourish/$recipeId'
    | '/path/$date'
    | '/nourish'
    | '/path'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/breathe'
    | '/dosha'
    | '/journal'
    | '/nourish'
    | '/path'
    | '/reset'
    | '/nourish/$recipeId'
    | '/path/$date'
    | '/nourish/'
    | '/path/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BreatheRoute: typeof BreatheRoute
  DoshaRoute: typeof DoshaRoute
  JournalRoute: typeof JournalRoute
  NourishRoute: typeof NourishRouteWithChildren
  PathRoute: typeof PathRouteWithChildren
  ResetRoute: typeof ResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosha': {
      id: '/dosha'
      path: '/dosha'
      fullPath: '/dosha'
      preLoaderRoute: typeof DoshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nourish': {
      id: '/nourish'
      path: '/nourish'
      fullPath: '/nourish'
      preLoaderRoute: typeof NourishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nourish/': {
      id: '/nourish/'
      path: '/'
      fullPath: '/nourish/'
      preLoaderRoute: typeof NourishIndexRouteImport
      parentRoute: typeof NourishRoute
    }
    '/nourish/$recipeId': {
      id: '/nourish/$recipeId'
      path: '/$recipeId'
      fullPath: '/nourish/$recipeId'
      preLoaderRoute: typeof NourishRecipeIdRouteImport
      parentRoute: typeof NourishRoute
    }
    '/path/': {
      id: '/path/'
      path: '/'
      fullPath: '/path/'
      preLoaderRoute: typeof PathIndexRouteImport
      parentRoute: typeof PathRoute
    }
    '/path/$date': {
      id: '/path/$date'
      path: '/$date'
      fullPath: '/path/$date'
      preLoaderRoute: typeof PathDateRouteImport
      parentRoute: typeof PathRoute
    }
  }
}

interface NourishRouteChildren {
  NourishRecipeIdRoute: typeof NourishRecipeIdRoute
  NourishIndexRoute: typeof NourishIndexRoute
}

const NourishRouteChildren: NourishRouteChildren = {
  NourishRecipeIdRoute: NourishRecipeIdRoute,
  NourishIndexRoute: NourishIndexRoute,
}

const NourishRouteWithChildren =
  NourishRoute._addFileChildren(NourishRouteChildren)

interface PathRouteChildren {
  PathDateRoute: typeof PathDateRoute
  PathIndexRoute: typeof PathIndexRoute
}

const PathRouteChildren: PathRouteChildren = {
  PathDateRoute: PathDateRoute,
  PathIndexRoute: PathIndexRoute,
}

const PathRouteWithChildren = PathRoute._addFileChildren(PathRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BreatheRoute: BreatheRoute,
  DoshaRoute: DoshaRoute,
  JournalRoute: JournalRoute,
  NourishRoute: NourishRouteWithChildren,
  PathRoute: PathRouteWithChildren,
  ResetRoute: ResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
